//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolsCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToolsCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stlačte klávesovú skratku pre priradenie ku príkazu..
        /// </summary>
        internal static string FAppSettings_lShortcutHelp1 {
            get {
                return ResourceManager.GetString("FAppSettings_lShortcutHelp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neplatná klávesová skratka. Stlačte inú..
        /// </summary>
        internal static string FAppSettings_lShortcutHelp2 {
            get {
                return ResourceManager.GetString("FAppSettings_lShortcutHelp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iba krátka správa.
        /// </summary>
        internal static string Settings_DebugOnlyMessage {
            get {
                return ResourceManager.GetString("Settings_DebugOnlyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailné informácie.
        /// </summary>
        internal static string Settings_DebugDetail {
            get {
                return ResourceManager.GetString("Settings_DebugDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spadnutie programu (systémový dialóg).
        /// </summary>
        internal static string Settings_DebugCrash {
            get {
                return ResourceManager.GetString("Settings_DebugCrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prázdne okno.
        /// </summary>
        internal static string Settings_StartupEmpty {
            get {
                return ResourceManager.GetString("Settings_StartupEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posledný projekt.
        /// </summary>
        internal static string Settings_StartupLast {
            get {
                return ResourceManager.GetString("Settings_StartupLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte skratku zo zoznamu.
        /// </summary>
        internal static string Settings_SelectShortcut {
            get {
                return ResourceManager.GetString("Settings_SelectShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vykonali ste zmeny vyžadujúce reštartovanie programu.  Reštartovať program teraz?.
        /// </summary>
        internal static string Settings_RestartNow {
            get {
                return ResourceManager.GetString("Settings_RestartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmeny sa prejavia úplne až po reštartovaní programu..
        /// </summary>
        internal static string Settings_RestartLater {
            get {
                return ResourceManager.GetString("Settings_RestartLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota nemôže byť prázdna..
        /// </summary>
        internal static string InputBox_Empty {
            get {
                return ResourceManager.GetString("InputBox_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodnota je neplatná..
        /// </summary>
        internal static string InputBox_Invalid {
            get {
                return ResourceManager.GetString("InputBox_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba v súbore štýlov: Štýl {0} je zadefinovaný viackrát..
        /// </summary>
        internal static string Styles_Duplicate {
            get {
                return ResourceManager.GetString("Styles_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ovládacie prvky.
        /// </summary>
        internal static string ColorScheme_Controls {
            get {
                return ResourceManager.GetString("ColorScheme_Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Žiadna).
        /// </summary>
        internal static string Shortcut_None {
            get {
                return ResourceManager.GetString("Shortcut_None", resourceCulture);
            }
        }
    }
}
